### ISSUE TITLE
Is it possible to create the permalink structure from the filename structure?

### ISSUE THREAD

**Issue by saviomd** [assemble/grunt-assemble-permalinks#57]
My permalink config is

```
permalinks: {
    structure: ':path/index.html'
}
```

I set the path in the YFM of every file and it's working fine, the files are compiled like '/jogos/lista/index.html', '/jogos/buraco/index.html', etc
But I wanted to have something more automatic, I don't want to do this in every single html file.

I was looking for a way to have something like that

```
permalinks: {
    structure: ':basename/index.html'
}
```

So the name of the files would be something like "jogos__lista.html", "jogos__buraco.html" and I would have a way to intercept the basename and replace all "__" with "/".
Is this currently possible?
(I'm using assemble 0.4.41 and permalinks 0.3.6)

**Comment by LaurentGoderre** [comment]
@doowb this is a nice workaround but perhaps this should be built in
