### ISSUE TITLE
Jump links not working

### ISSUE THREAD

**Issue by ryanve** [assemble/grunt-assemble-permalinks#62]
I have permalinks like `:basename/index.html` and they work except that links to jumps don't work. Clicking them has no effect.

```html
<a href="#example">example</a>
``` 

If I manually go to the address bar and add `#example` to the URL then it jumps as expected. They also work if I open the raw html file. Is there a way to get them to work with the permalinks?

**Comment by jonschlinkert** [comment]
Closing based on age, and since this sounds like an HTML issue, probably not related to this module.
